### ISSUE TITLE
Revise some of the statistical concepts

### ISSUE THREAD

**Issue by tavareshugo** [CambridgeCentreForProteomics/course_expression_proteomics#16]
At some point it would be good to revise the nomenclature and description of some bits in the stats section. 
Not necessary for the initial run of the course, something to come back to at a later date. 

Some thoughts:

- We're conflating two concepts: parametric models and gaussian linear models. The gaussian linear model is a type of parametric model, but not all parametric models assume the data-generating process is described by a gaussian distribution. E.g. poisson, negative binomial, lognormal, etc. or even non-linear models can be parametric.
- I would avoid recommending the so-called "normality" and "heteroskedasticity" tests as they are fundamentally flawed ([see here](https://stats.stackexchange.com/a/2498/363002)). In particular, when dealing with large datasets as is often the case in bioinformatics, we're almost always guaranteed to have low p-values for these tests, rendering them useless. The QQ-plots I think are good enough. 
- "we will use a form of t-test" best if we say we are using a linear model. These models are indeed akin to t-tests (when only two groups are considered) or multiple ANOVA (when more than 2 groups are available), but it may be best if we use the general term.
- "empirical Bayes moderated t-test", not "t-test" just linear model.
- "Limma will automatically select a t-test or ANOVA test depending upon how many groups (i.e., conditions) we pass to our model." - again, I feel like we're confusing things. Limma isn't really fitting different types of models to the data. It's all basically a linear model akin to `lm(y ~ x)`. The main difference from a regular linear regression is how they estimate variance parameters, which borrows information across genes to account for low replicate numbers. We can maybe just say we are fitting a linear model. Later we can detail that there's two kinds of tests we can do - a test at the level of the whole model (which is akin to the F-test used in ANOVA) or at individual contrast models. In the case of two groups these two things are effectively the same. 
- The explanation of t-values and F-values I think is good. But again, maybe we need to think about how we can rephrase this. For example, t-values can be calculated from any linear model, they are not exclusive of a T-test. They are just a test statistic. But anyway, the explanations themselves are nice. 
- In the limma paper they say: "Moderated F-statistics that combine the t-statistics for all contrasts into an overall test of significance for each gene can also be used". So, rather than say we are doing an ANOVA test, we could perhaps say we are performing a type of F-test.

**Comment by tavareshugo** [comment]
Also introduce `write.fit()` to get output for all contrasts, with a global p-value correction. 
Disadvantage is that it doesn't return confidence intervals.

Alternatively, we could write a simple function to loop through the contrasts and run `topTable()` to bind all the results.

**Comment by TomSmithCGAT** [comment]
Following discussion with @Charl-Hutchings, @lmsimp & @csdaw, we've decided to simply the stats section to focus on a single pairwise comparison. This should keep focus on principles of linear models for statistical testing and `limma`, without getting too bogged down in the proceedure for performing multiple comparisons. The existing code for multiple contrasts will be moved to a 'supplementary' section and participants made aware of it.

I'll take responsibility for the stats re-write. We didn't agree precisely how the sup material should be presented,   e.g as section 8, alongside other sup material, or under a seperate sub-heading of Supplementary Material, with sections for each separate sup material. @tavareshugo, any thoughts on what would be better?

**Comment by tavareshugo** [comment]
In terms of organising the content, no strict preference. It might be easier for now to put it under a new header of "Extended Material" as you suggest, so people know it's not covered in the course. And link to it from the main section. 

If you want help or discussion about the stats part, let me know, happy to help as well.

**Comment by TomSmithCGAT** [comment]
Thanks, @tavareshugo. I'm working on a separate branch, so I think the best thing to do would be to request a code review from you when I issue the PR. Then we can work out any issues before the merge. I expect it'll be late next week at the earliest
