### ISSUE TITLE
Add comparison table for LFQ versus labelled

### ISSUE THREAD

**Issue by lmsimp** [CambridgeCentreForProteomics/course_expression_proteomics#19]
CC @TomSmithCGAT @csdaw @Charl-Hutchings

**Comment by lmsimp** [comment]
Add a section at the end of the beginning and also end of the course clarifying this example dataset is for TMT data, highlight what you'd do for LQF

**Comment by TomSmithCGAT** [comment]
When we discussed this earlier, @Charl-Hutchings pushed back strongly against making firm recommendations for a definitive set of 'methods' to use for LFQ at each stage of the workflow. 

I think we settled on the LFQ vs TMT table/text clarifying the important differences, how this manifests in the data and options for dealing with LFQ.
