### ISSUE TITLE
Add heatmap 

### ISSUE THREAD

**Issue by Charl-Hutchings** [CambridgeCentreForProteomics/course_expression_proteomics#21]
Decision to add heatmap after volcano plot visualisation of stats results. Use `pheatmap` function to do so. Heatmap will be restricted to significantly changing proteins for the selected pairwise stats comparison (M-phase vs. desynchronised) and will show log norm abundances.

@TomSmithCGAT I started doing this, but I've never used the function before. Since you'll teach this part, I've left the code with minimal arguments -- you can add in whichever you wish to discuss. For the rest, I've added a link to where they can find more information on pheatmap and how to customise.

**Comment by TomSmithCGAT** [comment]
Thanks @Charl-Hutchings. I'm working on the stats on a separate branch, so probably best if we avoid both working on that notebook together to avoid conflicts. I'll pull in the latest commits to my branch.

**Comment by TomSmithCGAT** [comment]
Done. Seee #24
