### ISSUE TITLE
Reduce redundancy in data files

### ISSUE THREAD

**Issue by tavareshugo** [CambridgeCentreForProteomics/course_expression_proteomics#25]
At the moment we have data files duplicated:

* `materials/data`  and `course_files/data`
* `materials/output` and `course_files/preprocessed`

Instead, we can use the `here` package to save/load the files from the `course_files/preprocessed` directory only. That way we can eliminate the data files from the `materials` folder. 

The syntax is, for example: 

```r
here::here("course_files/preprocessed/lesson01.rda")
```

What the `here::here()` function will do is crawl up the directory structure and when it finds an Rproj file (which exists at the root of our repo), it will consider that the starting directory.

**Comment by TomSmithCGAT** [comment]
I'm definitely in favour of using `here` in general. 

I against having the `.rda` files in the repo given they aren't amenable to version control and there's a risk they could be updated quite often (I've done so a few times already!). However, I understand keeping them in might be the best solution available taking into account the needs of the participants/developers/website rendering. Let's discuss offline and I'll summarise here.

**Comment by TomSmithCGAT** [comment]
Resolved with #26
