### ISSUE TITLE
Add separate notebook for R packages and books

### ISSUE THREAD

**Issue by lmsimp** [CambridgeCentreForProteomics/course_expression_proteomics#9]
I think we should add a separate notebook after data and setup in the welcome section dedicated to explaining what packages we will use in this course and reference them and all the vignettes here. Bioconductor, R and `QFeatures` are fundamental to the course so I think we should make this clear at the beginning.

**Comment by TomSmithCGAT** [comment]
After discussion, no longer required since e.g `QFeatures` is described where needed
